apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: project-one
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: project-one
  endpoints:
    - port: http
      path: /metrics
      interval: 15s